(function () {
  'use strict';
  const model = window.CrewBIQNavigationModel;
  if (!model) throw new Error('CrewBIQNavigationModel is required');

  const demo = {
    driver:{name:'Izzet',headline:'Your road, in focus.',sub:'A calm view of this week’s work and what needs attention next.',metrics:[['Net pay','$2,184.60','+8.4% this week'],['Gross','$5,420','6 completed loads'],['Loaded miles','2,740','318 deadhead'],['RPM','$1.98','Above 30-day avg']],chips:['Truck 204 · Cascadia','PTI complete','All records synced']},
    owner_op:{name:'Izzet',headline:'Your truck is earning.',sub:'Revenue, costs and readiness in one operational view.',metrics:[['Gross','$7,840','+11.2% this week'],['Net','$3,965','50.6% margin'],['Fuel','$1,426','$0.52 / mile'],['Reserve','$684','Maintenance funded']],chips:['Truck 204 · Active','2 receipts to review','Audit data 94% complete']},
    fleet:{name:'Izzet',headline:'Your fleet is moving.',sub:'Exceptions rise to the top. Everything healthy stays quiet.',metrics:[['Active trucks','12','11 currently moving'],['Drivers','14','13 available'],['Gross','$68.4k','42 active loads'],['Exceptions','3','1 needs attention']],chips:['11 of 12 PTIs complete','42 loads in motion','Mileage evidence synced']}
  };
  const descriptions={load:'Create and track active work',disputes:'Resolve exceptions and payment issues',scan:'Capture a document for OCR',pti:'Inspection status and history',fuel:'Fuel stops and receipt capture',service:'Maintenance and repair activity',expenses:'Costs and reimbursements',report:'Export operational reports',stats:'Performance trends',deductions:'Weekly and fixed deductions',fleet:'Vehicle status and performance',drivers:'Driver roster and readiness',community:'Your trusted work links',settings:'Account and workspace preferences'};
  const state={role:'driver',page:'home',history:[],linkFilter:'all',query:'',chartSelection:null};
  const $=id=>document.getElementById(id);
  const main=$('main'),title=$('pageTitle'),eyebrow=$('pageEyebrow'),back=$('backButton');

  const paths={home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3v-9.5Z',work:'M4 7h16v12H4zM8 7V4h8v3M8 12h8',truck:'M3 7h11v10H3zM14 11h4l3 3v3h-7M7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z',team:'M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 2.13a4 4 0 0 1 0 7.75',money:'M3 6h18v12H3zM7 14h.01M17 10h.01M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',back:'M19 12H5m7 7-7-7 7-7',close:'M6 6l12 12M18 6 6 18',plus:'M12 5v14M5 12h14',load:'M4 7h16v13H4zM8 7V4h8v3',expenses:'M4 5h16v14H4zM4 9h16M8 15h3',scan:'M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M8 12h8',pti:'M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7l8-4Zm-3 9 2 2 4-5',fuel:'M5 3h10v18H5zM8 7h4M15 8h2l2 2v7a2 2 0 0 0 2 2',service:'M14 6a4 4 0 0 0-5 5L3 17l4 4 6-6a4 4 0 0 0 5-5l-3 1-2-2 1-3Z',disputes:'M12 3 3 20h18L12 3Zm0 6v5m0 3h.01',community:'M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7.5l-1 1M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7.5l1-1',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm7-3.5 2-1-2-3-2 .5-1.5-1L15 5h-6l-.5 2.5-1.5 1L5 8l-2 3 2 1v2l-2 1 2 3 2-.5 1.5 1L9 21h6l.5-2.5 1.5-1 2 .5 2-3-2-1v-2Z',search:'M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm10 2-4.35-4.35',empty:'M5 7h14v12H5zM8 4h8M9 11h6',error:'M12 3 3 20h18L12 3Zm0 6v5m0 3h.01'};
  function icon(name){const d=paths[name]||paths.grid;return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${d}"/></svg>`;}
  document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
  function label(page){return {home:'Today',work:'Work',truck:'Truck',team:'Team',money:'Money',functions:'Functions',community:'Links',states:'System states',settings:'Account'}[page]||model.PAGE_REGISTRY[page]&&page.charAt(0).toUpperCase()+page.slice(1)||'Preview';}
  function visibleGroups(){return model.visibleFunctionGroups(state.role);}
  function item(page){return visibleGroups().flatMap(g=>g.items).find(i=>i.page===page);}

  function renderRoleSwitch(){
    $('roleSwitch').innerHTML=[['driver','Driver'],['owner_op','Owner-Op'],['fleet','Fleet']].map(([id,text])=>`<button data-role="${id}" class="${state.role===id?'active':''}" aria-pressed="${state.role===id}">${text}</button>`).join('');
    $('currentRoleLabel').textContent={driver:'Driver',owner_op:'Owner-Op',fleet:'Fleet'}[state.role];
  }
  function renderNav(){
    const destinations=model.bottomDestinationsForRole(state.role);
    const navItem=p=>`<button class="rail-item ${state.page===p?'active':''}" data-route="${p}">${icon(p)}<span>${label(p)}</span></button>`;
    $('desktopNav').innerHTML=destinations.map(navItem).join('');
    const mobile=[destinations[0],destinations[1],'quick',destinations[2],destinations[3]];
    $('bottomNav').innerHTML=mobile.map(p=>p==='quick'?`<button class="bottom-item quick" data-quick aria-label="Quick Add">${icon('plus')}</button>`:`<button class="bottom-item ${state.page===p?'active':''}" data-route="${p}">${icon(p)}<span>${label(p)}</span></button>`).join('');
  }
  function sectionHead(kicker,heading,action='View all'){return `<div class="section-head"><div><span class="section-kicker">${kicker}</span><h2>${heading}</h2></div><button class="text-button">${action}</button></div>`;}
  function spark(){return `<svg class="spark" viewBox="0 0 68 30"><defs><linearGradient id="sparkFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#60a5fa" stop-opacity=".25"/><stop offset="1" stop-color="#60a5fa" stop-opacity="0"/></linearGradient></defs><path class="fill" d="M0 25 9 20 18 22 28 12 38 16 48 7 58 10 68 2V30H0Z"/><path d="M0 25 9 20 18 22 28 12 38 16 48 7 58 10 68 2"/></svg>`;}
  function homeView(){
    const d=demo[state.role];const quick=state.role==='driver'?[['load','Add Load'],['pti','Start PTI'],['scan','Scan Document']]:state.role==='fleet'?[['load','Add Load'],['fleet','Fleet status'],['scan','Scan Document']]:[['load','Add Load'],['fuel','Add Fuel'],['service','Log Service']];
    return `<div class="view"><section class="hero"><div class="hero-copy"><span class="section-kicker">Good morning, ${d.name}</span><h2>${d.headline.replace(/(focus|earning|moving)\./,'<em>$1.</em>')}</h2><p>${d.sub}</p></div><div class="hero-meta">${d.chips.map((c,i)=>`<span class="status-chip ${i===1&&state.role==='fleet'?'warn':''}"><i></i>${c}</span>`).join('')}</div></section>
    ${sectionHead('Live snapshot','This week','Performance')}
    <section class="metrics">${d.metrics.map(m=>`<article class="metric"><span class="metric-label">${m[0]}</span><strong>${m[1]}</strong><small class="${m[2].startsWith('+')?'up':''}">${m[2]}</small>${spark()}</article>`).join('')}</section>
    ${sectionHead('Interactive analytics','This week in motion','Touch or hover a day')}
    <section class="analytics-grid" id="analyticsGrid" aria-label="${state.role} analytics"></section>
    ${sectionHead('Move faster','Quick actions','Customize')}
    <section class="quick-actions">${quick.map(q=>`<button class="action-card" data-tool="${q[0]}"><span class="action-icon">${icon(q[0])}</span><span><strong>${q[1]}</strong><small>${descriptions[q[0]]}</small></span></button>`).join('')}</section>
    ${sectionHead('Operations','Recent activity')}
    <section class="content-grid"><article class="panel"><div class="loads-list">${[['CBQ-2841','Chicago, IL → Dallas, TX','In transit','$1,840'],['CBQ-2838','Memphis, TN → Joliet, IL','Delivered','$1,260'],['CBQ-2834','Gary, IN → Columbus, OH','Delivered','$980']].map((l,i)=>`<div class="load-row"><div class="load-id"><strong>${l[0]}</strong><small>${i?'Yesterday':'Today · 8:40 AM'}</small></div><div class="route"><b>${l[1]}</b><small>${i?486:924} loaded miles</small></div><span class="status ${i?'':'transit'}">${l[2]}</span><span class="money">${l[3]}</span></div>`).join('')}</div></article><aside class="panel"><div class="pulse-list"><div class="pulse-item"><i class="pulse-dot"></i><div><strong>PTI records complete</strong><small>Last inspection 6:42 AM</small></div></div><div class="pulse-item"><i class="pulse-dot"></i><div><strong>Mileage evidence synced</strong><small>Updated 4 minutes ago</small></div></div><div class="pulse-item"><i class="pulse-dot warn"></i><div><strong>2 documents need review</strong><small>Receipts detected by OCR</small></div></div></div></aside></section></div>`;
  }
  function operationalSummary(page){
    const summaries={
      work:state.role==='fleet'?[['Active loads','42','Across 11 trucks'],['Next exception','38 min','Driver response due'],['Missing docs','6','BOL / POD review']]:[['Active load','1','Chicago → Dallas'],['Next stop','184 mi','Fuel and rest'],['Missing docs','2','Receipt / POD']],
      truck:[['PTI','Complete','6:42 AM'],['Fuel','62%','Est. 430 miles'],['Maintenance','4,800 mi','Until service']],
      money:state.role==='driver'?[['Net','$2,184','This week'],['RPM','$1.98','Above average'],['Receipts','2','Pending review']]:[['Net','$3,965','This week'],['RPM','$1.98','Fleet average'],['Receipts','2','Pending review']],
      team:[['Trucks moving','11','of 12 active'],['Drivers ready','13','1 off duty'],['Exceptions','3','1 urgent']]
    };
    return `<section class="hub-summary" aria-label="${label(page)} operational summary">${(summaries[page]||[]).map(signal=>`<div class="summary-item"><span>${signal[0]}</span><strong>${signal[1]}</strong><small>${signal[2]}</small></div>`).join('')}</section>`;
  }
  function domainView(page){
    const groupName={work:'Work',truck:'Truck',team:'Team',money:'Money'}[page];const group=visibleGroups().find(g=>g.label===groupName);
    const copy={work:'Keep every load and document moving.',truck:'Your equipment, ready for the road.',team:'See the fleet without chasing updates.',money:'Know what the work is worth.'}[page];
    return `<div class="view"><div class="hub-intro"><div><span class="section-kicker">${groupName} command center</span><h2>${copy}</h2></div><p>Focused tools, clear status and no business logic duplicated in the shell.</p></div>${operationalSummary(page)}<section class="tool-grid">${(group?.items||[]).map(i=>`<button class="tool-card" data-tool="${i.page}"><span class="arrow">↗</span><span class="tool-icon">${icon(i.page)}</span><h3>${i.label}</h3><p>${descriptions[i.page]||'Open capability preview'}</p></button>`).join('')}</section>${page==='truck'||page==='team'?readinessPanel():''}</div>`;
  }
  function readinessPanel(){return `${sectionHead('Audit readiness','Evidence health','Open status')}<section class="metrics"><article class="metric"><span class="metric-label">Mileage evidence</span><strong>100%</strong><small class="up">Synced</small></article><article class="metric"><span class="metric-label">Fuel receipts</span><strong>18 / 20</strong><small>2 need review</small></article><article class="metric"><span class="metric-label">PTI compliance</span><strong>94%</strong><small class="up">Healthy</small></article><article class="metric"><span class="metric-label">Open exceptions</span><strong>3</strong><small>1 urgent</small></article></section>`;}
  function functionsView(){return `<div class="view"><div class="hub-intro"><div><span class="section-kicker">Capability map</span><h2>Everything CrewBIQ can do.</h2></div><p>Role-aware tools come directly from the accepted navigation model.</p></div>${visibleGroups().map(g=>`<section class="group-section"><div class="group-title"><h2>${g.label}</h2><span>${g.items.length} tools</span></div><div class="function-grid">${g.items.map(i=>`<button class="function-card" data-tool="${i.page}"><span class="tool-icon">${icon(i.page)}</span><span><strong>${i.label}</strong><small>${descriptions[i.page]}</small></span></button>`).join('')}</div></section>`).join('')}<section class="panel"><span class="section-kicker">Prototype coverage</span><h2>Loading, empty and error states</h2><p style="color:var(--muted)">Review calm system feedback without touching production workflows.</p><button class="primary-button" data-route="states">Review interface states</button></section></div>`;}
  const links=[{name:'DAT Load Board',url:'one.dat.com',cat:'dispatch',fav:true},{name:'Pilot Flying J',url:'pilotflyingj.com',cat:'fuel',fav:false},{name:'FMCSA Portal',url:'portal.fmcsa.dot.gov',cat:'documents',fav:true},{name:'Truckstop',url:'truckstop.com',cat:'dispatch',fav:false},{name:'Fleet Maintenance',url:'fleet.example',cat:'maintenance',fav:false},{name:'Carrier Accounting',url:'accounting.example',cat:'accounting',fav:false}];
  function linksView(){const cats=['all','favorites','dispatch','fuel','documents','maintenance'];const filtered=links.filter(l=>(state.linkFilter==='all'||state.linkFilter==='favorites'&&l.fav||l.cat===state.linkFilter)&&(`${l.name} ${l.url}`.toLowerCase().includes(state.query.toLowerCase())));return `<div class="view"><div class="hub-intro"><div><span class="section-kicker">Resources & account</span><h2>Your road essentials, one tap away.</h2></div><p>Mock cards demonstrate the extracted Links capability. Nothing is saved.</p></div><div class="links-toolbar"><label class="search-box">${icon('search')}<input id="linkSearch" type="search" value="${state.query}" placeholder="Search links" aria-label="Search links"></label><button class="primary-button" data-demo="Add Link">＋ Add link</button></div><div class="filter-row">${cats.map(c=>`<button class="filter-button ${state.linkFilter===c?'active':''}" data-filter="${c}">${c[0].toUpperCase()+c.slice(1)}</button>`).join('')}</div>${sectionHead('Saved resources',`${filtered.length} links`,'Manage')}<section class="links-grid">${filtered.map(l=>`<article class="link-card"><div class="link-top"><span class="tool-icon">${icon('community')}</span><button class="favorite" data-demo="Favorite" aria-label="${l.fav?'Remove from':'Add to'} favorites">${l.fav?'★':'☆'}</button></div><h3>${l.name}</h3><p>${l.url}</p><div class="link-footer"><span class="link-category">${l.cat}</span><button class="open-link" data-demo="Open link">Open ↗</button></div></article>`).join('')||`<article class="state-card"><div><span class="state-visual">${icon('empty')}</span><h3>No matching links</h3><p>Try another search or category.</p></div></article>`}</section></div>`;}
  function statesView(){return `<div class="view"><div class="hub-intro"><div><span class="section-kicker">Calm feedback</span><h2>Every system state has a clear next step.</h2></div><p>Visual treatment only. No transport or persistence is implemented.</p></div><section class="states-grid"><article class="state-card"><div><span class="state-visual"><i class="spinner"></i></span><h3>Syncing records</h3><p>Keeping the user informed without blocking work.</p></div></article><article class="state-card"><div><span class="state-visual"><span class="empty-lines"><i></i><i></i><i></i></span></span><h3>Nothing here yet</h3><p>A useful empty state with one obvious action.</p></div></article><article class="state-card"><div><span class="state-visual error-visual">${icon('error')}</span><h3>Couldn’t sync</h3><p>Work remains safe. Retry when connection returns.</p></div></article><article class="state-card chart-empty-preview">${CrewBIQCharts.zeroStateMarkup('No earnings recorded this week')}</article></section></div>`;}
  function toolView(page){const i=item(page)||{label:label(page)};return `<div class="view"><div class="hub-intro"><div><span class="section-kicker">Read-only capability preview</span><h2>${i.label}</h2></div><p>${descriptions[page]||'This production capability remains unchanged.'}</p></div><section class="panel"><div class="state-card" style="border:0;background:none;box-shadow:none"><div><span class="state-visual">${icon(page)}</span><h3>Production workflow intentionally not connected</h3><p>This shell demonstrates navigation and hierarchy only.</p><button class="primary-button" data-demo="Preview action" style="margin-top:18px">Preview action</button></div></div></section></div>`;}
  function render(){
    renderRoleSwitch();renderNav();const primary=['home','work','truck','team','money','functions','community','states'];
    const isBack=!primary.includes(state.page);back.classList.toggle('show',isBack);document.querySelector('.page-identity').classList.toggle('has-back',isBack);
    title.textContent=label(state.page);eyebrow.textContent=state.role==='owner_op'?'Owner-Operator workspace':`${state.role[0].toUpperCase()+state.role.slice(1)} workspace`;
    main.innerHTML=state.page==='home'?homeView():['work','truck','team','money'].includes(state.page)?domainView(state.page):state.page==='functions'?functionsView():state.page==='community'?linksView():state.page==='states'?statesView():toolView(state.page);
    if(state.page==='home')CrewBIQCharts.renderDashboard($('analyticsGrid'),state.role);
    main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});
  }
  function navigate(page,fromBack=false){if(page==='settings') page='settings';if(!fromBack&&state.page!==page)state.history.push(state.page);state.page=page;render();}
  function openQuick(){const base=[['load','Load'],['expenses','Expense'],['pti','PTI'],['scan','Document']];if(state.role!=='driver')base.splice(2,0,['fuel','Fuel'],['service','Service']);$('quickGrid').innerHTML=base.map(i=>`<button class="quick-item" data-demo="Add ${i[1]}">${icon(i[0])}<span>${i[1]}</span></button>`).join('');$('sheetScrim').classList.add('show');$('quickSheet').classList.add('show');$('sheetScrim').setAttribute('aria-hidden','false');$('quickSheet').setAttribute('aria-hidden','false');}
  function closeQuick(){$('sheetScrim').classList.remove('show');$('quickSheet').classList.remove('show');$('sheetScrim').setAttribute('aria-hidden','true');$('quickSheet').setAttribute('aria-hidden','true');}
  let toastTimer;function toast(message){clearTimeout(toastTimer);$('toast').textContent=`${message} · prototype only`;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200);}
  document.addEventListener('click',e=>{const route=e.target.closest('[data-route]');const role=e.target.closest('[data-role]');const tool=e.target.closest('[data-tool]');if(route)navigate(route.dataset.route);if(role){state.role=role.dataset.role;$('roleControl').classList.remove('open');$('roleToggle').setAttribute('aria-expanded','false');if(state.page==='truck'&&state.role==='fleet')state.page='team';if(state.page==='team'&&state.role!=='fleet')state.page='truck';render();}if(tool)navigate(tool.dataset.tool);if(e.target.closest('[data-quick]'))openQuick();const filter=e.target.closest('[data-filter]');if(filter){state.linkFilter=filter.dataset.filter;render();}const demoButton=e.target.closest('[data-demo]');if(demoButton){closeQuick();toast(demoButton.dataset.demo);}});
  document.addEventListener('input',e=>{if(e.target.id==='linkSearch'){state.query=e.target.value;const caret=e.target.selectionStart;main.innerHTML=linksView();const next=$('linkSearch');next.focus();next.setSelectionRange(caret,caret);}});
  main.addEventListener('crewbiq:chart-select',e=>{state.chartSelection=e.detail;});
  back.addEventListener('click',()=>{state.page=state.history.pop()||'home';render();});$('functionsButton').addEventListener('click',()=>navigate('functions'));$('roleToggle').addEventListener('click',()=>{const open=$('roleControl').classList.toggle('open');$('roleToggle').setAttribute('aria-expanded',String(open));});$('closeQuick').addEventListener('click',closeQuick);$('sheetScrim').addEventListener('click',closeQuick);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('roleControl').classList.remove('open');$('roleToggle').setAttribute('aria-expanded','false');closeQuick();}});
  function enter(){ $('launch').classList.add('is-gone');$('shell').classList.add('is-ready');$('shell').setAttribute('aria-hidden','false');render(); }
  $('skipLaunch').addEventListener('click',enter);setTimeout(enter,1650);
})();
